language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .[all]
# add services needed
services:
  - mongodb
# command to run tests
script:
  - pytest
